name: 'Setup OpenHSP environment'
description: 'Set up your GitHub Actions workflow with a specific version of OpenHSP.'
author: 'BonyChops'
inputs:
  build-targets:
    description: 'Specify the list of build targets.'
    required: false
    default: |
      hspcmp
      hsp3cl
  openhsp-version:
    description: 'Specify the OpenHSP version.'
    required: false
    default: 'v3.6'
  parallel-build-num:
    description: 'Specify the number of parallel builds.'
    required: false
    default: '3'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
