name: Check Actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build_hsp:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup OpenHSP
        uses: ./
      - run: hspcmp ./tests/sample.hsp -o./tests/sample.ax
      - id: run_hsp
        run: hsp3cl ./tests/sample.ax
      - name: test
        run: |
          test "${{ steps.run_hsp.outputs.stdout }}" = "Hello, HSP!"
