name: Check Actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build_hsp:
    runs-on: ubuntu-latest
    name: Build HSP
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup OpenHSP
        uses: ./
      - name: Build Sample Source
        run: hspcmp ./tests/sample.hsp -o./tests/sample.ax
      - name: Run Sample Source
        id: run_hsp
        run: |
          echo "HSP_RESULT<<EOF" >> $GITHUB_OUTPUT
          hsp3cl ./tests/sample.ax >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Test
        run: |
          test "${{ steps.run_hsp.outputs.HSP_RESULT }}" = "Hello, HSP!"
